import{i as c,S as p}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();function m(n){return n.hits.map(({webformatURL:r,largeImageURL:i,tags:e,likes:t,views:s,comments:u,downloads:f})=>`<a href="${i}" class='gallery-link'
          ><li class='item'>
            <img  class='gallery-img' src="${r}  alt="${e}" />
            <p><b>Likes:</b>${t}</p>
            <p><b>Views:</b>${s}</p>
            <p><b>Comments:</b>${u}</p>
            <p><b>Downloads:</b>${f}</p>
          </li></a
        >`).join("")}const a=document.querySelector(".form");document.querySelector(".container");const l=document.querySelector(".gallery");a.addEventListener("submit",d);function d(n){n.preventDefault(),l.innerHTML="";const o=n.currentTarget.elements.query.value;o===""&&c.warning({title:"",message:"Please, fill in search field",position:"center"}),g(o).then(r=>{r.hits.length===0?c.error({title:"",message:"Sorry, there are no images matching your search query. Please try again!",position:"center"}):l.insertAdjacentHTML("beforeend",m(r))}).catch(r=>console.log(r)),a.reset()}function g(n){const i=`https://pixabay.com/api/?key=42059071-0978dc0d7158b742eee7c30f5&q=${encodeURIComponent(n)}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(i).then(e=>{if(!e.ok)throw new Error(e.statusText);return e.json()})}const h={captions:!0,captionSelector:"self",captionPosition:"bottom",captionDelay:250};let y=new p(".gallery a");y.on("show.simplelightbox",h);
//# sourceMappingURL=index.js.map
